### ISSUE TITLE
Fix Camera View Port on Resize

### ISSUE THREAD

**Issue by PyroFlareX** [OpMonTeam/OpMon-Archive#102]
Allow the window to be resized and just viewport accordingly.

https://www.sfml-dev.org/tutorials/2.5/graphics-view.php

**Comment by PyroFlareX** [comment]
Added resize support, but screen only stretches for now. Likely needs the sf::RenderTexture to be removed in favor of drawing directly to the window. Resizing via views will then hopefully be a trivial matter.

**Comment by milkyroute** [comment]
Just copying something from the Discord since I think it's useful to put it here : 
I know it is possible to extend the view, but I don't think I want to extend the player's view area on the map, because it means that with a large screen you can see parts or the map which can be normally inaccessible, or that I want to hide for now, because it will be shown in a further point in the story. We will think of it, but it may be a little problematic. However, if you have ideas to solve this problem, extending the view according to the window size would be a great idea.
