### ISSUE TITLE
When will the mac version be released?

### ISSUE THREAD

**Issue by speicherwerk** [OpMonTeam/OpMon-Archive#94]

**Comment by milkyroute** [comment]
Since neither me or @navet56 have a mac, we can't compile the game on it right now. So, right now, the only thing you can do is to build the game yourself. If you can do it, you can execute <code>cmake --build . --target package --config Release</code> to create a mac package, and then give it to us. With this, we could release the mac version.
I must admit, we kind of forgot the mac version, so I will make an announcement on the Discord server to find someone who can compile the game on mac.

**Comment by milkyroute** [comment]
A development Mac version has been released on the website (https://opmon-game.ga/downloads.html).
We'll try to do it quicker for the next version.
