### ISSUE TITLE
Organize the Repository

### ISSUE THREAD

**Issue by PyroFlareX** [OpMonTeam/OpMon-Archive#99]
If this would be possible, can the repository be a bit better organized?

For example, have versions be milestones rather than projects. Have projects be big TODO features, such as battle system, engine improvements. Also, having so many tags kinda clutters up the issues and makes them hard to sort. Just having "Enhancements", "Bugs", and "Next Version" are fine.

I believe that organizing the repo will help new contributors find things to help with more effectively.

**Comment by milkyroute** [comment]
The versions already are milestones, we use both. Milestones for Issues and Pull Requests, and projects for being clear on what we have to do to release the version. I must be honest: I have difficulties to create a project for big TODO features because I just kind of "jump" in it without really knowing how I have to do, then I do my thing and clean up the code after it.
For the labels, I will sort some things, but I won't leave only three because for us priorities and some other information are important. But I agree I have to clean them up a bit.
**Edit :** After some time, I realized "priority" labels were totally useless since there is milestones. Sorry for this.
